(function(){
  function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function checks(labels,selected){return labels.map((label,index)=>`<span class="check">${selected===(['ok','ng','ask'][index])?'☑':'□'} ${label}</span>`).join('　');}
  function descriptionMarkup(value,template){const text=String(value??'').replace(/\r\n?/g,'\n');if(!text)return '';const measurer=document.createElement('div');measurer.className=`sheet-card print-sheet template-${template}`;Object.assign(measurer.style,{position:'absolute',left:'-10000px',top:'0',visibility:'hidden',width:'calc((297mm - 2 * 7mm - 4mm) / 2 + 32mm)',height:'calc((210mm - 2 * 7mm - 4mm) / 2)',aspectRatio:'auto'});const lines=[];text.split('\n').forEach((paragraph,index,paragraphs)=>{const description=document.createElement('div');description.className='sheet-description';description.style.flex='none';description.textContent=paragraph||' ';measurer.append(description);document.body.append(measurer);const node=description.firstChild;const chars=Array.from(paragraph);const grouped=[];let current='';let top=null;let offset=0;for(const character of chars){const range=document.createRange();range.setStart(node,offset);range.setEnd(node,offset+character.length);const rect=range.getClientRects()[0];if(rect&&top!==null&&Math.abs(rect.top-top)>1){grouped.push(current);current='';}if(rect)top=rect.top;current+=character;offset+=character.length;}if(current||!grouped.length)grouped.push(current);lines.push(...grouped);description.remove();});measurer.remove();return lines.map(esc).join('<br>');}
  function markup(sheet,template,blank=false){const value=v=>blank?'':(v||'');return `<div class="sheet-top"><img class="nagare-logo" src="assets/nagare-key/logo.png" alt="ながれキー"><span class="tenkey-mark">#天キーVol.12</span><h2 class="sheet-name">${esc(value(sheet.keyboardName))}</h2><div class="sheet-exhibitor"><span class="exhibitor-label">EXHIBITOR / HANDLE</span><span class="exhibitor-value">${esc(value(sheet.exhibitor))}</span></div></div><div class="sheet-meta"><div class="meta-item"><span class="meta-label">KEY SWITCH</span><span class="meta-value">${esc(value(sheet.switchName))}</span></div><div class="meta-item"><span class="meta-label">KEYCAPS</span><span class="meta-value">${esc(value(sheet.keycaps))}</span></div></div><div class="sheet-description">${descriptionMarkup(value(sheet.description),template)}</div><div class="permission-grid"><div><span class="permission-label">試し打ち</span><span class="permission">${checks(['OK','NG','声かけて'],sheet.typing)}</span></div><div><span class="permission-label">撮影・SNS投稿</span><span class="permission">${checks(['OK','NG'],sheet.photo)}</span></div></div><div class="sheet-footer"></div>`;}
  function fitDescription(card){const element=card.querySelector('.sheet-description');if(!element)return 'normal';const levels=['normal','small','smaller','minimum'];element.classList.remove(...levels);let chosen='minimum';for(const level of levels){element.classList.add(level);if(element.scrollHeight<=element.clientHeight+1){chosen=level;break;}}element.classList.add(chosen);return chosen;}
  function lineCount(element){const range=document.createRange();range.selectNodeContents(element);return Array.from(range.getClientRects()).filter(rect=>rect.width>0&&rect.height>0).length;}
  function fitKeyboardName(card,singleLine=false){const element=card.querySelector('.sheet-name');if(!element)return 'name-normal';const levels=['name-normal','name-small','name-smaller','name-minimum'];element.classList.remove(...levels);element.classList.toggle('name-single-line',singleLine);let chosen='name-normal';for(let index=0;index<levels.length;index++){element.classList.add(levels[index]);const lines=lineCount(element);const fits=singleLine?element.scrollWidth<=element.clientWidth+1:(index===0?lines<=1:lines<=2);if(fits){chosen=levels[index];break;}chosen=levels[index];}element.classList.add(chosen);return chosen;}
  window.SheetCard={markup,fitDescription,fitKeyboardName};
})();
